### ISSUE TITLE
Get "products" doesn't work with multiple filters

### ISSUE THREAD

**Issue by AlaaSelim** [woothemes/wc-api-php#1]
hello,

i'm trying to get products using multiple filters but i always get this message:
Error: Invalid Signature - provided signature does not match [woocommerce_api_authentication_error]

even though i'm using the same keys to get other data like orders successfully, but when i try to get products using filters like category, sku, page..etc i get that invalid signature message

any idea why i'm getting this message?

thanks

**Comment by claudiosmweb** [comment]
> multiple filters

How?
Show me.

**Comment by AlaaSelim** [comment]
hi, thanks for your fast reply

i'm just using an array that has the filters like this:

try {
  $params = array(
    "filter[limit]" => 15,
    "filter[category]" => "Music",
    "page"=> 1
    );
	 $data = $woocommerce->get('products',  $params);
	 print_r($data);

} catch (Exception $e) {
	print_r($e->getMessage());
}

**Comment by claudiosmweb** [comment]
Of course don't works... Wrong filters...

Use:

```php
$params = [
    'filter' => [
        'limit' => 15,
        'category' => 'Music',
    ],
    'page' => 1,
];
```

**Comment by AlaaSelim** [comment]
Not working, i'm still getting that error message 
but when i remove category filter it works

```php
$params = [
    'filter' => [
        'limit' => 15,
        'post_status' => 'publish'
    ],
    'page' => 1,
];
```

i have replaced category with post_status=>'publish' and it works.
i get that message when using category filter
how to make it work with category?
