### ISSUE TITLE
IIS not accepting POST/PUT but GET works

### ISSUE THREAD

**Issue by Trevald** [woothemes/wc-api-php#11]
Developing local with API v3 everything works fine. On production server, which is an IIS GET requests works fine but POST and PUT generates "woocommerce_api_authentication_error" => "Signature error, not matching" (free translating from Swedish).

The IIS server should be fine with POST (not absolutely sure about PUT). Any ideas?

**Comment by claudiosmweb** [comment]
Make sure that POST and PUT are enabled on your IIS server.
But this does not seem a problem with this wrapper only on your server.
You can try another wrappers to confirm that the problem is your server: http://woothemes.github.io/woocommerce-rest-api-docs/#official-libraries

**Comment by Trevald** [comment]
I agree that the problem is the server and not the wrapper. But I thought you may have encountered something similar before. PUT and POST are enabled as far as I can tell. The funny thing is that PUT works but POST don't. The other way around is what I would have expected. Is there any difference in how POST and PUT handles authentication? Was thinking maybe something with the encoding goes wrong with the POST request. Seems far fetch to me but at this point I'm willing to accept anything.

**Comment by Trevald** [comment]
Sorry, forgot to mention that we managed to get PUT to work. Did the same thing to enable POST but still wont work.

**Comment by claudiosmweb** [comment]
> But I thought you may have encountered something similar before

Nop, I never use IIS.

> Is there any difference in how POST and PUT handles authentication?

The same authentication for POST, GET, PUT and DELETE.
