### ISSUE TITLE
API - Invalid response json

### ISSUE THREAD

**Issue by apuestaya** [woothemes/wc-api-php#13]
Hi and thanks for this great API client for Woocommerce.
I'm getting  **'Invalid JSON returned'** because response is null when i do calls on live..
**I'm using Versión 2.5.5 and this issue is related with issue  #10**

**On localhost**
- it is working fine on localhost PUT, POST, GET...
- It is working fine if i do calls under same domain setted up with vhost and xampp

**On live server (InmotionHosting)**
- I created read/write  API key and signature. 
- i tested url in browser to see if it is building endpoint properly and it is.
- i only can get product count with API when i do requests under same domain.
- Same issue with call methods GET, PUT, DELETE and POST
- Server has enable allow_url_fopen = ON 
- Server has enable CURL
- I can do calls with google API without issues

Kindly, help me if somebody has same issue.
Thank you very much :+1:

**Comment by ad-on-is** [comment]
https://github.com/woothemes/wc-api-php/issues/10#issuecomment-196741534
For me, updating solved the problem.

Maybe your php.ini settings on live server are to low. i.e `memory_limit` or `max_execution_time`

**Comment by apuestaya** [comment]
Hi @ad-on-is, what plugin did you updated. i updated woocommerce to 2.5.5 version but i still get this issue.
Thank you for your help

**Comment by ad-on-is** [comment]
I updated woocommerce from 2.5.2 to 2.5.5.
Check your timeouts in both your live php.ini and your API-client. Also check the memory_limit in php.ini

**Comment by apuestaya** [comment]
i have memory_limit 512M and timeout is 60
i increase values in php.ini and still getting this error.

**Comment by ad-on-is** [comment]
What timeout, memory_limit and max_execution_time do you have on your local environment?
I'd recommend setting timeout to 1000

**Comment by apuestaya** [comment]
I increase values to max..
Ok, i see **http_code is 400 on live server** and local is 200. I printed them with this code in line 373 HttpClient.php :

echo "<pre>";
print_r(curl_getinfo ($this->ch));

**API docs says:**
- Invalid requests, such as using an unsupported HTTP method will result in 400 Bad Request.

What am i doing bad if i'm just doing this call:
$count = $this->Marketplace_Services->woocommerceAPI->get('products/count');
echo "<pre>";
print_r($count);

**Comment by apuestaya** [comment]
Hi, i installed a copy in different server and domain, i checked phpinfo and there are **min values** for memory_limit, max_execution_time ...But it is ok.
It is working fine for calls like (PUT, POST...) and it can access with keys created and site url into woo site admin installed on server that does not work on live and it is getting 400 error code with error invalid json printed by lookForErrors() .

It is not working on Inmotion Hosting because i tried to access from different domain and same server having bad request 400. Although i can access from different domain and different server.

Although i was not solved it, this issue can be closed or wait after i got a solution to share to other people.

Thank you very much @ad-on-is  for all your information and your time.

**Comment by danielemesh** [comment]
@apuestaya any luck with the error?

**Comment by apuestaya** [comment]
Hi daniel, It was some Hosting setting but it was out of my hands. I contacted to my hosting provider and they said they can not support beacuse plan does not include development support.

**I needed it to self-sign** and i fixed just copying Woo API files to use them on my new plugin.
Now, i need it to allow other websites connect with my database through this great API but i can't for this reason.
I attach file.

USAGE (based on woo API docs)
$data = [            
                'type' => 'variable',
                'attributes' => $product_attrs,
                'variations' => $variations				
		];
        $Fast_Import = new Fast_ImportCSV($post_id);
        $Fast_Import->save_product_meta( $post_id, $data );
	$Fast_Import->save_variations( $post_id, $data);

[class-stock-updater-fast-import-product.zip](https://github.com/woothemes/wc-api-php/files/253938/class-stock-updater-fast-import-product.zip)

**Comment by claudiosmweb** [comment]
Update to the last version.

**Comment by bigopl** [comment]
@apuestaya can you tell us what hosting setting was it? I have the same problem.

**Comment by apuestaya** [comment]
@bigopli was with InmotionHosting company.
