### ISSUE TITLE
Notice: Undefined offset: 1 in HttpClient.php on line 244

### ISSUE THREAD

**Issue by bokorir** [woothemes/wc-api-php#15]
Hi,

A notice appears when you update/create a product. I think it happens on all post/put method.

Problem: automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 244

`list($key, $value) = \explode(': ', $line);`

The header contains a line `HTTP/1.1 200 OK` and this string doesn't contains `:`.

**Comment by claudiosmweb** [comment]
Fixed in #12
