### ISSUE TITLE
Get data and post it to another woocommerce API website.

### ISSUE THREAD

**Issue by JohnSHA1** [woothemes/wc-api-php#19]
Hello,
I have 2 websites and installed woocommerce on both websites. I have API keys of both the websites. The thing I want to do is when I request for the particular ID on the first website, the returned data should post that item on the another website. For example,

```
$site_main = new Client(
    'https://abc.biz/', 
    'ck_zbc', 
    'cs_zbc',
     [
        'version' => 'v3',
        'ssl_verify'=> 'false'
    ]
    
);

 $get_result = $site_main ->get('products/17640');

$site_another= new Client(
    'https://xyz.com/', 
    'ck_123', 
    'cs_456',
     [
        'version' => 'v3',
        'ssl_verify'=> 'false'
    ]
);

$site_another->post('products',$get_result);
```

Basically get data from one API and post into another one. The problem is the data are filed but some are not like images and other stuffs! Any solution?

**Comment by claudiosmweb** [comment]
Just change the data before update. Like images, if you don't send the ID they will be uploaded again...
But here is not a support channel. Good luck.
