### ISSUE TITLE
something is wrong when using filters

### ISSUE THREAD

**Issue by AlaaSelim** [woothemes/wc-api-php#2]
I'm trying to use filters with no luck, i keep getting 

Error: Invalid Signature - provided signature does not match [woocommerce_api_authentication_error]

I get that error every time i try to use filters like this:

```php
$params = [
    'filter' => [
        'created_at_min' => '2016-01-01',
        'created_at_max' => '2016-01-15',
    ],
    'page' => 1,
];
```
if i remove the dates filters it will work:

```php
$params = [
    'filter' => [
        'limit' => 15,
    ],
    'page' => 1,
];
```
category filter show the same message:
```php
$params = [
    'filter' => [
        'limit' => 15,
        'category' => 'Music',
    ],
    'page' => 1,
];

```
it will work if i remove it:
```php
$params = [
    'filter' => [
        'limit' => 15,
    ],
    'page' => 1,
];

```

**Comment by pixelpeter** [comment]
I experienced the same behavior.

It's only possible to use **one** of the `created_at_*` date filters.
Using both at the same time will git the authentication error.

**Comment by claudiosmweb** [comment]
Update to 1.0.1.
