### ISSUE TITLE
Product is not posted on second API

### ISSUE THREAD

**Issue by JohnSHA1** [woothemes/wc-api-php#20]
Hello,
I have 2 websites and installed woocommerce on both websites. I have API keys of both the websites. The thing I want to do is when I get particular product details on the first website, the returned data should post on the another website. For example,
```
$site_main = new Client(
    'https://abc.biz/', 
    'ck_zbc', 
    'cs_zbc',
     [
        'version' => 'v3',
        'ssl_verify'=> 'false'
    ]

);

 $get_result = $site_main ->get('products/17640');

$site_another= new Client(
    'https://xyz.com/', 
    'ck_123', 
    'cs_456',
     [
        'version' => 'v3',
        'ssl_verify'=> 'false'
    ]
);

$site_another->post('products',$get_result);

```

So, Get data from one API and post into another one.  Well, this do not create product on second website. It's keep saying that :

```
Undefined offset: 1 in /var/www/html/autosync/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 242
```

I'm not asking for support but help. I have tried it many times and then decided to post here.

Thank you!

**Comment by claudiosmweb** [comment]
Here is not a support channel, please stop!
