### ISSUE TITLE
Filters not Working

### ISSUE THREAD

**Issue by sagargulati** [woothemes/wc-api-php#21]
```
<?php
$woocommerce = new Client(
    'http://mywpsite.com', 
    'ck_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 
    'cs_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    [
        'wp_api' => true,
        'version' => 'wc/v1',
    ]);

try {
$params = [
  'filter' => [
    'limit' => '2'
  ],
];
$getData = $woocommerce->get("/products/", $param);
echo json_encode($getData, JSON_PRETTY_PRINT);
} catch (HttpClientException $e) {
	$data['status'] = 'error';
	echo json_encode($data, JSON_PRETTY_PRINT);

// OUTPUTS ALL PRODUCTS (Filters not working)
```
Filters just doesn't work

Woocommerce = v2.6.0 beta 2
WC API = 3.1.0
WP REST API = v1.1.1 (Latest from Github) [https://github.com/woothemes/wc-api-php]

**Comment by claudiosmweb** [comment]
` WC API = 3.1.0` wrong man, really wrong, since you used ` 'wp_api' => true,` and `'version' => 'wc/v1',` you are requesting our new REST API.
And we don't have any `'filter' => [` in this API.

Use the Old API v3 for now and wait for the docs...

**Comment by sagargulati** [comment]
As far i remember, the rest API have (or will have) you only said its possible in WP REST API.
https://wordpress.org/support/topic/wc-api-angularjs-cod-basic-features?replies=15#post-8419128

Can you please confirm it, on the release will WP REST API will have all the filters and features like WC.

Since WP API is the Latest and WC API v3 is old, we want to stick to WP REST API, so can you please answer this questions:
1) Will the WP REST API will have the filters like the WC API in the next release?
2) Since it's the latest, it is more compatible than the WC API?
3) The sub categories of product categories features is in WC API or WP Rest API?


Thanks!

**Comment by claudiosmweb** [comment]
@sagargulati wait for the docs.

**Comment by sagargulati** [comment]
@claudiosmweb : sure i will, can you please confirm and answer the questions atleast we asked so that we can confirm that filters are gonna work with WP REST API as well?

Thanks!

**Comment by claudiosmweb** [comment]
@sagargulati nop, here is not a support forum and the wrong place to talk about the REST API.
If you have issues or found a bug in this wrapper, I'll be happy to answer you ;)
