### ISSUE TITLE
Issue with authentication Consumer Key is missing

### ISSUE THREAD

**Issue by M144-Coder** [woothemes/wc-api-php#22]
I am using this library v 1.1.1 under HTTP and disabled mod_security but the library always throw this exception:

Caught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Error: oauth_consumer_key parameter is missing [woocommerce_api_authentication_error]'

Here is my code:

        $woocommerce = new Client(
                SERVER_URL, API_KEY, API_SECRET, ['version' => 'v3', 'timeout' => 20, 'verify_ssl' => false, 'query_string_auth' => false]
        );

**Comment by claudiosmweb** [comment]
>  but the library always throw this exception:

It's not the library fault. Need to check in your server if is removing the query params before hit WooCommerce.
Not an issue in this wrapper too.

**Comment by M144-Coder** [comment]
It seems that the issue is with the wrapper because I used a java desktop application (code below) to test the API and it works (using scribe java OAuth Library) or the server doesn't allow curl to the same server because the script is in the same server with WooCOmmerce, any suggestions to access wooCommerce directly without the Rest API?


`try {
        OAuthService service = new ServiceBuilder()
            .apiKey(API_KEY)
            .apiSecret(API_SECRET)
            .debugStream(System.out)
            .signatureType(SignatureType.QueryString)
            .build(new WooCommerceApi());

        OAuthRequest request = new OAuthRequest(Verb.GET, SERVER_URL + "/wc-api/v3/products/", service);

        service.signRequest(new Token("", ""), request);
        Response response = request.send();

        System.out.println(response.getCode());
        System.out.println(response.getBody());
} catch (Exception ex) {
    ex.printStackTrace();
}`

**Comment by claudiosmweb** [comment]
@M144-Coder if is showing `oauth_consumer_key parameter is missing` is because your server is removing it.
