### ISSUE TITLE
About Usage

### ISSUE THREAD

**Issue by Ceranimo** [woothemes/wc-api-php#23]
Hi,

Thank you for this comprehensive library.

Can you explain usage of this library more detailed? For example how to setup, how to get or delete a order, usage of methods etc. 

I newly started to use Woocommerce api and I stuck at beginning. 

Thank you!

**Comment by claudiosmweb** [comment]
Just read the WooCommerce API docs: https://woothemes.github.io/woocommerce-rest-api-docs/
