### ISSUE TITLE
How use it?

### ISSUE THREAD

**Issue by pws2016** [woothemes/wc-api-php#24]
Hello,
i download your script but how we can use it? have an example (php files)?
thanks

**Comment by mikejolley** [comment]
Examples are in the docs https://woothemes.github.io/woocommerce-rest-api-docs/?php#request-response-format

**Comment by pws2016** [comment]
i read this, but how i can use your script? i not find : '/vendor/autoload.php';
??!

**Comment by mikejolley** [comment]
Thats part of composer. If you're not using composer you don't need it. Examples are in https://github.com/woothemes/wc-api-php#woocommerce-api---php-client

**Comment by pws2016** [comment]
yes i not use composer can expalin me more? or give me a simple php code?

**Comment by mikejolley** [comment]
I've linked you to 2 resources with PHP example code. You need to have some experience working with REST APIs and PHP to get this working - it is aimed at developers.
