### ISSUE TITLE
Client call returns [rest_no_route]

### ISSUE THREAD

**Issue by viktorivanov** [woothemes/wc-api-php#25]
Hi,
my WordPress version is 4.5.2 with WooCommerce version 2.5.5 and I'm trying to make a call to the Rest API. I have installed and enabled the [WordPress REST API (Version 2)](https://wordpress.org/plugins/rest-api/) and generated API Key for WooCommerce.

```php
$woocommerce = new Client(
    'http://wp-rest-api.dev', // it's a local domain
    '...1235bd6', // consumer key
    '...ecb6412', // consumer secret
    [
        'wp_api' => true, // Enable the WP REST API integration
        'version' => 'wc/v1' // WooCommerce WP REST API version
    ]
);
```

and when I try to call an API endpoint, eg. products
```php
$woocommerce->get('products');
```
I'm getting ```Error: No route was found matching the URL and request method [rest_no_route]```

Can someone please point me on to the right direction.

**Comment by viktorivanov** [comment]
I found where my problem is:
```WooCommerce (WC) 2.6+ is fully integrated with the WordPress REST API...```

That means I have to use the legacy v3 API as my WC version is < 2.6.x

Sorry, my bad.

**Comment by Babelfisch** [comment]
Same error occurs on WC 2.6.4. Rest-API is enabled and:

```curl -X OPTIONS https://my-host/wp-json/wc/v1/orders```

works fine but the class doesn't work.
