### ISSUE TITLE
undefined index 'position' in class-wc-api-products.php on r. 2524

### ISSUE THREAD

**Issue by DCdeBrabander** [woothemes/wc-api-php#26]
While fetching products via the client-AP,I I got the many notices which breaks the valid json response. Probably because I programmatically import (many) products via methods like wp_insert_post and add_post_meta()/update_post_meta() (since saving via this client is, for some reason, so inconvenient in debugging and speed) . And since I never thought of giving my attributes some position, it throws these notices.

**original**: 
'position'  => (int) $attribute['position'],

**My 'fix':**
'position'  => isset($attribute['position']) ? (int) $attribute['position'] : 0,

**Comment by claudiosmweb** [comment]
This don't seems to be an issue in this wrapper. Why are you reporting it here?
