### ISSUE TITLE
Erro 500

### ISSUE THREAD

**Issue by bzca** [woothemes/wc-api-php#27]
Boas,

Podemos falar em português ? 
Antes de mais parabéns pelo teu trabalho.

Estava a tentar experimentar a tua wc-api-php mas não consigo obter nada. Sempre que tento fazer get ou post de alguma coisa recebo o erro 500. Será problema do lado do hosting ? 

Com um client (postman) consigo obter os get request mas não consigo fazer post request, recebo um problema de autenticação.

Com a tua wc-api-php ao efectuar a ligação não recebo nenhum erro mas depois ao efectuar a query recebo sempre erro 500. Será que me podias ajudar? 

Obrigado.

**Comment by claudiosmweb** [comment]
> Podemos falar em português ? 

Não. Nem é útil para as outras pessoas que usam esse wrapper.
