### ISSUE TITLE
Woocommerce Rest Api Fatal Error Getting Issue

### ISSUE THREAD

**Issue by SachinOxilo** [woothemes/wc-api-php#28]
I have following errors :-

Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'cURL Error: Failed to connect to sachinbasendra.com port 443: Connection refused' in /home/u732858947/public_html/app/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:365 Stack trace: #0 /home/u732858947/public_html/app/vendor/automattic/woocommerce/src/WooCommerce/Client.php(82): Automattic\WooCommerce\HttpClient\HttpClient->request('products', 'GET', Array, Array) #1 /home/u732858947/public_html/app/api.php(16): Automattic\WooCommerce\Client->get('products') #2 {main} thrown in /home/u732858947/public_html/app/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php on line 365

please help me thanks in advanced

**Comment by claudiosmweb** [comment]
Not an issue with this wrapper:

> cURL Error: Failed to connect to sachinbasendra.com port 443: Connection refused

This here is in your environment. So fix it.

**Comment by SachinOxilo** [comment]
Ok thanks i have resolve it but now came this error ?

Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Syntax error' in vendor\automattic\woocommerce\src\WooCommerce\HttpClient\HttpClient.php on line 331

**Comment by SachinOxilo** [comment]
How to resolve it please let me confirm...

**Comment by claudiosmweb** [comment]
@SachinOxilo your store/site is throwing errors.

**Comment by Blair2004** [comment]
have the same issue, when using Woo Rest API to save image.

**Comment by Blair2004** [comment]
If found the issue. Make sure the data you submit is correct @SachinOxilo

**Comment by andrewevans** [comment]
Same issue. Is there a way to debug this better? Works on my local just fine, but on my remote dev box it doesn't. I installed cURL via WHM's interface. Is it related to that? I expect a cURL error if that is the case, though. Here's my error log when hitting a page that does any Woocommerce command even the most basic like ```Woocommerce::get('')```, however `class_exists("Woocommerce")` does return `true`.
`[2017-05-18 22:22:26] local.ERROR: Automattic\WooCommerce\HttpClient\HttpClientException: Syntax error in /home/aendr/laravel50/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:340
Stack trace:
#0 /home/aendr/laravel50/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php(379): Automattic\WooCommerce\HttpClient\HttpClient->processResponse()
#1 /home/aendr/laravel50/vendor/automattic/woocommerce/src/WooCommerce/Client.php(82): Automattic\WooCommerce\HttpClient\HttpClient->request('orders', 'GET', Array, Array)
#2 /home/aendr/laravel50/vendor/pixelpeter/laravel5-woocommerce-api-client/src/WoocommerceClient.php(58): Automattic\WooCommerce\Client->get('orders', Array)
#3 /home/aendr/laravel50/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(221): Pixelpeter\Woocommerce\WoocommerceClient->get('orders')
#4 /home/aendr/laravel50/app/Http/Controllers/SomeController.php(33): Illuminate\Support\Facades\Facade::__callStatic('get', Array)
`

**Comment by dinhnguyenjp** [comment]
> Ok thanks i have resolved it but now came this error ?

Can you tell me how to fix isssue? :(
Many thanks!
