### ISSUE TITLE
Woocommerce Rest Api Syntax Error 

### ISSUE THREAD

**Issue by SachinOxilo** [woothemes/wc-api-php#29]
Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Syntax error' in /home/u732858947/public_html/woo-api/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:331

Here is my code calling...
<?php
require __DIR__ . '/vendor/autoload.php';
use Automattic\WooCommerce\Client;
$woocommerce = new Client(
    'http://mysite.com',
     'ck_e67e9...................................................................',
     'cs_0896a...................................................................',
    [
        'wp_api' => true,
        'version' => 'wc/v1'
    ]
);
print_r($woocommerce->get('products'));
?>

Please help ?

**Comment by claudiosmweb** [comment]
The "Syntax error" is in your store/site response, your site is throwing errors.

> Fatal error: Uncaught exception 'Automattic\WooCommerce\HttpClient\HttpClientException' with message 'Syntax error' in /home/u732858947/public_html/woo-api/vendor/automattic/woocommerce/src/WooCommerce/HttpClient/HttpClient.php:331

Do you know why have a Fatal error?
Because `Uncaught exception`, since you are not following the guide!

Where is the `try/catch` in our code?
So follow the guide, and debug it first!
