### ISSUE TITLE
Updating variation image by ID of existing image

### ISSUE THREAD

**Issue by kongper** [woothemes/wc-api-php#30]
I am not sure if this is a bug or a support issue:
I create a product with two variations. The first variation has an image, the second has no image. So far, all good. 
I GET the product and can see the id of the uploaded variation image. All good.
I want both variations to have the same image, so I update (PUT) the product, adding the image ID of the first variation to the second variation, and set position=0. But nothing happens. Other changed parameters are updated, just not the image. Am i doing something wrong, or is this a bug?

**Comment by claudiosmweb** [comment]
Not seems to be an issue with this wrapper.
