### ISSUE TITLE
Request parameters are not working.

### ISSUE THREAD

**Issue by spik3s** [woothemes/wc-api-php#32]
Hi,

I've noticed that actually most of the parameters listed in WooCommerce Api docs are not working for me.

I can filter product results by category using:
``$woocommerce->get('products', ['filter[category]' =>'my-category'])``

but when I'm trying parameters such as `order/orderby`, `search` (among other) I just get back basic response and the parameters are being ignored.

**Comment by claudiosmweb** [comment]
Of course not, since when this is an valid array?

See the right way to write the code:

```php
 $woocommerce->get('products', ['filter' => ['category' => 'my-category']])
```

**Comment by qroft** [comment]
Has this changed with the latest WC version? I just copied the line from @claudiosanches and the filter does not happen - instead i get all products.

**Comment by claudiosanches** [comment]
@qroft nop, but not all WooCommerce REST API versions uses `filter`, you should read the REST API doc for the correct REST API version that you are trying to use.
