### ISSUE TITLE
manage cart using api

### ISSUE THREAD

**Issue by vthinkmehul** [woothemes/wc-api-php#34]
any api for managing woocommerce cart using rest api?

**Comment by claudiosmweb** [comment]
You don't need to manage the cart, you can just create orders.

**Comment by vthinkmehul** [comment]
hello i want to get cart data in mobile application and set product in to
cart from mobile application using API.
is there any api for cart?

**Comment by claudiosmweb** [comment]
No need API for cart, you can use orders.
