### ISSUE TITLE
error 401 - woocommerce_rest_cannot_view in localhost

### ISSUE THREAD

**Issue by ghost** [woothemes/wc-api-php#344]
I am encountering authentication issues while trying to access the WooCommerce REST API over HTTP in a local development environment. The API consistently returns a 401 Unauthorized error, indicating a problem with the authentication process.

`{"code":"woocommerce_rest_cannot_view","message":"Sorry, you cannot list resources.","data":{"status":401}}`

i checked and change `ck_your_consumer_key:cs_your_consumer_secret` is ok but i got error.

i use wordpress in mac xampp with PHP 8.3

```
$this->client = new Client(
            $this->baseUrl,
            $this->ck,
            $this->cs,
            [
                'wp_api' => true,
                'version' => 'wc/v3',
                'timeout' => 0
            ]
        );
```

**Comment by ghost** [comment]
<img width="828" alt="Screenshot 2024-01-25 at 6 55 33 PM" src="https://github.com/woocommerce/wc-api-php/assets/30009591/0d27492a-3958-47ac-936c-b3c4211cd692">
<img width="733" alt="Screenshot 2024-01-25 at 6 55 45 PM" src="https://github.com/woocommerce/wc-api-php/assets/30009591/3982b2e3-5f6e-43fb-a09c-2b50cb24d61d">

**Comment by rrennick** [comment]
See https://woocommerce.github.io/woocommerce-rest-api-docs/#authentication-over-http.
