### ISSUE TITLE
Error: No route was found matching the URL and request method. [rest_no_route]

### ISSUE THREAD

**Issue by whitsey** [woothemes/wc-api-php#346]
I followed the guide and tried to create a category but I keep getting the error: **PHP Fatal error:  Uncaught Automattic\WooCommerce\HttpClient\HttpClientException: Error: No route was found matching the URL and request method. [rest_no_route]**

		// https://packagist.org/packages/automattic/woocommerce#user-content-client-class
		$options = ['verify_ssl' => false]; 
		
		$woocommerce = new Client(
			$settings["store_url"],
			$settings["consumer_key"],
			$settings["consumer_secret"],
			$options
		);

		// https://woocommerce.github.io/woocommerce-rest-api-docs/?php#create-a-product-category
		// POST /wp-json/wc/v3/products/categories
		$endpoint = "/wp-json/wc/v3/products/categories";
		
		$result = $woocommerce->post($endpoint, ['name' => $saveData["category"]]);

**Comment by rrennick** [comment]
See the [setup instructions](https://woocommerce.github.io/woocommerce-rest-api-docs/?php#create-a-product-category) and [rguments](https://woocommerce.github.io/woocommerce-rest-api-docs/?php#create-a-product-category) sections of the documentation.
