### ISSUE TITLE
Missing products when retrieving all products

### ISSUE THREAD

**Issue by rubensmz** [woothemes/wc-api-php#38]
I am using this PHP library to connect Microsoft Access with WooCommerce. Nevertheless, when retrieving all products some of them are missing. This is the function I am using:
```php
function getAllWCProducts(){
  //Get WooCommerce client
  $woocommerce = getWCClient();
  // 200 products per page
  $array = Array('posts_per_page' => 200);
  // Initialize counter
  $i = 1;
  // Initialize array
  $result = Array();
  // Execute a query while products are returned
  do{
      $page = $i;
      try {
        // Store every page in the array
        $result[$i] = $woocommerce->get('products', ['page'=>$page,'filter'=>$array]);
      } catch (Exception $e) {
        echo $e->getMessage();
      }
      $i++;
  }while(!empty($result[$i-1]));
  return $result;
}
```

In WooCommerce there are about 600 products. The function retrieves most of the products, but particularly, when post_per_page filter is set to 200 products with ID from 694 to 761 are not retrieved. And when post_per_page is set to 20, missing products ID goes from 694 to 818. 

I have been debugging the code throroughly and my conclusions are that $woocommerce->get() is the culprit. Nonetheless, I do not know if the mistake is either on the filter parameters or in the function design.

**Comment by claudiosmweb** [comment]
If something is missing, I don't see how is an issue with this wrapper.
It should be reported on https://wordpress.org/support/plugin/woocommerce

**Comment by rubensmz** [comment]
The issue is with this wrapper. WooCommerce works perfectly and does show every product perfectly. The issue is indeed with this client. 
If posts_per_page filter is changed to 10000, every product is correctly.

**Comment by rubensmz** [comment]
Is shown correctly*

**Comment by claudiosmweb** [comment]
The issue can be on the REST API and not this wrapper, for what you are saying, I don't see how this wrapper change the number of products or hide some product.
Just read the code here, it's not possible.

**Comment by rubensmz** [comment]
Understood. Thank you for your help.
