### ISSUE TITLE
Is there a problem with products route?

### ISSUE THREAD

**Issue by limeframe** [woothemes/wc-api-php#4]
Hi!
Is there a problem with products route?
I have tested : orders, customers, coupons , products/categories and all of them have a responses.
But when i try return Woocommerce::get('products'); terminate the  connection and i am getting a
 No data received

ERR_EMPTY_RESPONSE

Thanks

Very nice job

**Comment by limeframe** [comment]
So for debugging! I am getting the following error :

Whoops, looks like something went wrong.
1/1 HttpClientException in HttpClient.php line 303: Invalid JSON returned

    in HttpClient.php line 303
    at HttpClient->lookForErrors(null) in HttpClient.php line 345
    at HttpClient->processResponse() in HttpClient.php line 381
    at HttpClient->request('products/1330', 'GET', array(), array()) in Client.php line 82
    at Client->get('products/1330', array()) in WoocommerceClient.php line 59
    at WoocommerceClient->get('products/1330') in Facade.php line 218
    at Facade::__callStatic('get', array('products/1330')) in testController.php line 19
    at testController->index()
    at call_user_func_array(array(object(testController), 'index'), array()) in Controller.php line 76
    at Controller->callAction('index', array()) in ControllerDispatcher.php line 146
    at ControllerDispatcher->call(object(testController), object(Route), 'index') in ControllerDispatcher.php line 94
    at ControllerDispatcher->Illuminate\Routing\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
    at Pipeline->Illuminate\Routing\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
    at Pipeline->then(object(Closure)) in ControllerDispatcher.php line 96
    at ControllerDispatcher->callWithinStack(object(testController), object(Route), object(Request), 'index') in ControllerDispatcher.php line 54
    at ControllerDispatcher->dispatch(object(Route), object(Request), 'App\Http\Controllers\testController', 'index') in Route.php line 174
    at Route->runController(object(Request)) in Route.php line 140
    at Route->run(object(Request)) in Router.php line 703
    at Router->Illuminate\Routing\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
    at Pipeline->Illuminate\Routing\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
    at Pipeline->then(object(Closure)) in Router.php line 705
    at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 678
    at Router->dispatchToRoute(object(Request)) in Router.php line 654
    at Router->dispatch(object(Request)) in Kernel.php line 246
    at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Pipeline.php line 52
    at Pipeline->Illuminate\Routing\{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
    at CheckForMaintenanceMode->handle(object(Request), object(Closure))
    at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
    at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Pipeline.php line 32
    at Pipeline->Illuminate\Routing\{closure}(object(Request))
    at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
    at Pipeline->then(object(Closure)) in Kernel.php line 132
    at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 99
    at Kernel->handle(object(Request)) in index.php line 53

**Comment by pixelpeter** [comment]
I'm constantly working with the `products` resource and it's working fine.

Are you sure the product with the id `1330` exists ?

Have you tried it with a different `id `? Maybe something in the product data screws up the JSON response.

**Comment by limeframe** [comment]
Yes! You are semi-right! :)
I create a new product! I tried to call the product and i get back Invalid JSON returned.
I change the product title from Greel Language to English (latin characters) and i tried to call the product!
The product returned fine!
So the problem maybe is in the non-latin characters.

>If i change the automatic\woocommerce\HttpClient\HttpClient.php -> line 343 ,
from   ->    $parsedResponse = $this->decodeResponseBody($this->response->getBody());
to ->  $parsedResponse = $this->response->getBody();
i take back a result.

So probable the problem is in the decodeResponseBody function and greek characters

**Comment by pixelpeter** [comment]
I have no problem with getting products from the api having german umlauts (ä, ö, ü) in the title.

Also I have no problems with a title like "test product ä ö ü βήτα".

Please check your server and database configuration I everything is configured to work with utf-8.

Additionally try a direct call to the api on the console with `curl` or `wget`

**Comment by limeframe** [comment]
Everything on my server is configured to work with utf-8.
the direct call to the api with curl working fine!
Thanks
You can see the result 


{"products":[{"title":"\u0394\u03bf\u03ba\u03b9\u03bc\u03b1\u03c3\u03c4\u03b9\u03ba\u03cc \u03c0\u03c1\u03bf\u03ca\u03cc\u03bd","id":1336,"created_at":"2016-01-24T17:48:08Z","updated_at":"2016-01-24T17:48:52Z","type":"simple","status":"publish","downloadable":false,"virtual":false,"permalink":"https:\/\/aldr.do.gr\/product\/lets-test-a-product\/","sku":"111","price":"11","regular_price":"11","sale_price":null,"price_html":"<span class=\"amount\">&pound;11.00<\/span>","taxable":false,"tax_status":"taxable","tax_class":"","managing_stock":false,"stock_quantity":null,"in_stock":true,"backorders_allowed":false,"backordered":false,"sold_individually":false,"purchaseable":true,"featured":false,"visible":true,"catalog_visibility":"visible","on_sale":false,"product_url":"","button_text":"","weight":null,"dimensions":{"length":"","width":"","height":"","unit":"cm"},"shipping_required":true,"shipping_taxable":true,"shipping_class":"","shipping_class_id":null,"description":"<p>test product description<\/p>\n","short_description":"<p>dddd<\/p>\n","reviews_allowed":true,"average_rating":"0.00","rating_count":0,"related_ids":[],"upsell_ids":[],"cross_sell_ids":[],"parent_id":0,"categories":["testcat"],"tags":[],"images":[{"id":0,"created_at":"2016-01-24T18:13:43Z","updated_at":"2016-01-24T18:13:43Z","src":"https:\/\/aldr.do.gr\/wp-content\/plugins\/woocommerce\/assets\/images\/placeholder.png","title":"Placeholder","alt":"Placeholder","position":0}],"featured_src":"","attributes":[],"downloads":[],"download_limit":0,"download_expiry":0,"download_type":"","purchase_note":"","total_sales":0,"variations":[],"parent":[],"grouped_products":[],"menu_order":0},{"title":"Updated title","id":1330,"created_at":"2016-01-18T20:10:24Z","updated_at":"2016-01-24T17:29:03Z","type":"variable","status":"publish","downloadable":false,"virtual":false,"permalink":"https:\/\/aldr.do.gr\/product\/test2\/","sku":"","price":null,"regular_price":"","sale_price":null,"price_html":"","taxable":false,"tax_status":"taxable","tax_class":"","managing_stock":false,"stock_quantity":null,"in_stock":true,"backorders_allowed":false,"backordered":false,"sold_individually":false,"purchaseable":true,"featured":false,"visible":true,"catalog_visibility":"visible","on_sale":false,"product_url":"","button_text":"","weight":null,"dimensions":{"length":"","width":"","height":"","unit":"cm"},"shipping_required":true,"shipping_taxable":true,"shipping_class":"","shipping_class_id":null,"description":"","short_description":"","reviews_allowed":true,"average_rating":"0.00","rating_count":0,"related_ids":[],"upsell_ids":[],"cross_sell_ids":[],"parent_id":0,"categories":["\u0394\u03bf\u03ba\u03b9\u03bc\u03b1\u03c3\u03c4\u03b9\u03ba\u03ae \u03ba\u03b1\u03c4\u03b7\u03b3\u03bf\u03c1\u03af\u03b1"],"tags":[],"images":[{"id":0,"created_at":"2016-01-24T18:13:43Z","updated_at":"2016-01-24T18:13:43Z","src":"https:\/\/aldr.do.gr\/wp-content\/plugins\/woocommerce\/assets\/images\/placeholder.png","title":"Placeholder","alt":"Placeholder","position":0}],"featured_src":"","attributes":[{"name":"\u03a7\u03c1\u03ce\u03bc\u03b16","slug":"colore","position":0,"visible":true,"variation":true,"options":["120gr","2","7"]}],"downloads":[],"download_limit":0,"download_expiry":0,"download_type":"","purchase_note":"","total_sales":0,"variations":[{"id":1331,"created_at":"2016-01-18T20:10:24Z","updated_at":"2016-01-24T17:29:03Z","downloadable":false,"virtual":false,"permalink":"https:\/\/aldr.do.gr\/product\/test2\/?attribute_pa_colore=2-3","sku":"","price":"","regular_price":"","sale_price":null,"taxable":false,"tax_status":"taxable","tax_class":"","managing_stock":false,"stock_quantity":null,"in_stock":true,"backordered":false,"purchaseable":false,"visible":false,"on_sale":false,"weight":null,"dimensions":{"length":"","width":"","height":"","unit":"cm"},"shipping_class":"","shipping_class_id":null,"image":[{"id":0,"created_at":"2016-01-24T18:13:43Z","updated_at":"2016-01-24T18:13:43Z","src":"https:\/\/aldr.do.gr\/wp-content\/plugins\/woocommerce\/assets\/images\/placeholder.png","title":"Placeholder","alt":"Placeholder","position":0}],"attributes":[{"name":"\u03a7\u03c1\u03ce\u03bc\u03b16","slug":"colore","option":"2-3"}],"downloads":[],"download_limit":0,"download_expiry":0}],"parent":[],"grouped_products":[],"menu_order":0},{"title":"test","id":1327,"created_at":"2016-01-18T17:38:33Z","updated_at":"2016-01-18T20:22:17Z","type":"variable","status":"publish","downloadable":false,"virtual":false,"permalink":"https:\/\/aldr.do.gr\/product\/test\/","sku":"","price":"111","regular_price":"","sale_price":null,"price_html":"<span class=\"amount\">&pound;111.00<\/span>","taxable":false,"tax_status":"taxable","tax_class":"","managing_stock":false,"stock_quantity":null,"in_stock":true,"backorders_allowed":false,"backordered":false,"sold_individually":false,"purchaseable":true,"featured":false,"visible":true,"catalog_visibility":"visible","on_sale":false,"product_url":"","button_text":"","weight":null,"dimensions":{"length":"","width":"","height":"","unit":"cm"},"shipping_required":true,"shipping_taxable":true,"shipping_class":"","shipping_class_id":null,"description":"","short_description":"","reviews_allowed":true,"average_rating":"0.00","rating_count":0,"related_ids":[],"upsell_ids":[],"cross_sell_ids":[],"parent_id":0,"categories":[],"tags":[],"images":[{"id":0,"created_at":"2016-01-24T18:13:43Z","updated_at":"2016-01-24T18:13:43Z","src":"https:\/\/aldr.do.gr\/wp-content\/plugins\/woocommerce\/assets\/images\/placeholder.png","title":"Placeholder","alt":"Placeholder","position":0}],"featured_src":"","attributes":[{"name":"\u03a7\u03c1\u03ce\u03bc\u03b16","slug":"colore","position":0,"visible":true,"variation":true,"options":["#2","1","120gr"]}],"downloads":[],"download_limit":0,"download_expiry":0,"download_type":"","purchase_note":"","total_sales":0,"variations":[{"id":1328,"created_at":"2016-01-18T17:38:33Z","updated_at":"2016-01-18T20:22:17Z","downloadable":false,"virtual":false,"permalink":"https:\/\/aldr.do.gr\/product\/test\/?attribute_pa_colore=120-1000gr","sku":"001","price":"111","regular_price":"111","sale_price":null,"taxable":false,"tax_status":"taxable","tax_class":"","managing_stock":true,"stock_quantity":8,"in_stock":true,"backordered":false,"purchaseable":true,"visible":true,"on_sale":false,"weight":null,"dimensions":{"length":"","width":"","height":"","unit":"cm"},"shipping_class":"","shipping_class_id":null,"image":[{"id":0,"created_at":"2016-01-24T18:13:43Z","updated_at":"2016-01-24T18:13:43Z","src":"https:\/\/aldr.do.gr\/wp-content\/plugins\/woocommerce\/assets\/images\/placeholder.png","title":"Placeholder","alt":"Placeholder","position":0}],"attributes":[{"name":"\u03a7\u03c1\u03ce\u03bc\u03b16","slug":"colore","option":"120-1000gr"}],"downloads":[],"download_limit":0,"download_expiry":0},{"id":1329,"created_at":"2016-01-18T17:38:33Z","updated_at":"2016-01-18T20:22:17Z","downloadable":false,"virtual":false,"permalink":"https:\/\/aldr.do.gr\/product\/test\/?attribute_pa_colore=1","sku":"","KONSTANTINOSs-iMac:woostorage elstKONSTANTINOSs-iMac:woostorage elstKONSTANTINOSs-iMac:woostorage elstKONSTANTINOSs-iMac:woostorage elstKONSTANTINOSs-iMac:woostorage elstKONSTANTINOSs-iMac:woostorage elstKONSTANTINOSs-iMac:woostorage elstKONSTANTINOSs-iMac:woostorage elst

**Comment by pixelpeter** [comment]
Maybe @claudiosmweb can help here because I don't have any other idea (right now). Sorry.

**Comment by limeframe** [comment]
I agree :-) 
Thank you very much for your time :-)

**Comment by claudiosmweb** [comment]
@limeframe can you please export some of this products?
So I can test it.

**Comment by limeframe** [comment]
Yes ofcource @claudiosmweb.

[export_product-2016_01_25-09_17_43.csv.zip](https://github.com/woothemes/wc-api-php/files/102974/export_product-2016_01_25-09_17_43.csv.zip)


Thanks

**Comment by pixelpeter** [comment]
Well, your exported products are working for me.

Doesn't seem to be a data issue.

**Comment by limeframe** [comment]
ok! I installed a new clean WP with woocommerce for testing purposes!
Take a look to the following video (screen capture) 
http://mobisoft.gr/video-for-api/

**Comment by claudiosmweb** [comment]
@limeframe please, try our master now with this patch ^

**Comment by limeframe** [comment]
@claudiosmweb its working now (after your changes)!
I will test more later and i will keep you informed
Thanks thanks and thanks again 
Kostas

**Comment by claudiosmweb** [comment]
I believe this is enough. I'm creating a new release.
Thanks :)
