### ISSUE TITLE
 '/vendor/autoload.php' missing

### ISSUE THREAD

**Issue by montyvesselinov** [woothemes/wc-api-php#42]
I am trying to setup WC-API; however i do not have /vendor/autoload.php in my directory structure. I have WP and WC installed. What am I missing?

**Comment by montyvesselinov** [comment]
I see 'composer' is required; it is not clear in the instructions;

Note the following fails; it works only if options are not specified; how the api works? Does it work?

require __DIR__ . '/vendor/autoload.php';

use Automattic\WooCommerce\Client;

$woocommerce = new Client(
    'http://example.com', // Your store URL
    'consumer_key', // Your consumer key
    'consumer_secret', // Your consumer secret
    [
        'wp_api' => true, // Enable the WP REST API integration
        'version' => 'wc/v1' // WooCommerce WP REST API version
    ]
);

**Comment by claudiosmweb** [comment]
![screenshot from 2016-09-13 00-16-19](https://cloud.githubusercontent.com/assets/1264099/18460381/5d2b86e8-7947-11e6-9a1d-e661caa854d2.png)

> It works only if options are not specified

Old version of PHP?
This is a syntax for PHP 5.4 or later.

**Comment by claudiosmweb** [comment]
Closing since you did not replied it and don't looks like an error with this code, looks like you did not installed using composer.
