### ISSUE TITLE
Order Meta

### ISSUE THREAD

**Issue by gumwp** [woothemes/wc-api-php#44]
We have created a custom order_meta value to tag specific orders and are trying to query only those specific orders without returning every order and then looping through them.  I can not determine the correct parameters to retrieve order_meta value.  I have tried adding url parameters:
&meta_key=meta_value.  We also set the filter[meta]=true.  

With the new API V1, I see there is a filter option, although unsure how to set the query args?
filter - Use WP Query arguments to modify the response; private query vars require appropriate authorization.

How can I retrieve only the orders with a set order_meta value?  Thanks for your help.

**Comment by claudiosmweb** [comment]
Not an issue with this wrapper.
And you should read the [WooCommerce REST API docs](https://woothemes.github.io/woocommerce-rest-api-docs/) or user the [proper support channel](https://wordpress.org/support/plugin/woocommerce).

**Comment by tomkeysers** [comment]
@gumwp had any luck with it yet? Looking for something similar.
