### ISSUE TITLE
filter search not working

### ISSUE THREAD

**Issue by MQuach17** [woothemes/wc-api-php#46]
using `$products = $woocommerce->get('products',['filter'=>['search'=>'somesearchterm']]);`,
`$products = $woocommerce->get('products',['search'=>'somesearchterm']);`, and
`$products = $woocommerce->get('products',['per_page'=>1]);` do not return expected results

returns default results

**Comment by MQuach17** [comment]
`$products = $woocommerce->get('products',['search'=>'somesearchterm'])` also does not return expected results

**Comment by claudiosmweb** [comment]
Not an issue with this wrapper.
And you should read the [WooCommerce REST API docs](https://woothemes.github.io/woocommerce-rest-api-docs/) or user the [proper support channel](https://wordpress.org/support/plugin/woocommerce).

**Comment by MQuach17** [comment]
if anyone finds this and has the same problem its because of the `wp_api` variable and the `version` were not correct. I changed 
`        $woocommerce = new Client(
            'http://example.com/', 
            'ck_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 
            'cs_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            [
                'version' => 'v3',
            ]
        );`

to 

`        $woocommerce = new Client(
            'http://example.com/', 
            'ck_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', 
            'cs_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
            [
                'wp_api' => true
                'version' => 'wc/v1',
            ]
        );`
