### ISSUE TITLE
Posting product works but always comes back with "no response from server"

### ISSUE THREAD

**Issue by MQuach17** [woothemes/wc-api-php#47]
` try{
            print_r($woocommerce->post('products',$data));
        }catch(HttpClientException $e){
            $e->getMessage(); // Error message.
            $e->getRequest(); // Last request data.
            $e->getResponse(); // Last response data.
}`

is returning "no response from server" and response code 0 but when it posts show up on the front end.

**Comment by jb000** [comment]
`
//HttpClientException->getMessage()
Syntax error


//HttpClientException->getRequest()
Automattic\WooCommerce\HttpClient\Request Object ( [url:Automattic\WooCommerce\HttpClient\Request:private] => https://www.example.com/wc-api/v3/products [method:Automattic\WooCommerce\HttpClient\Request:private] => POST [parameters:Automattic\WooCommerce\HttpClient\Request:private] => Array ( ) '[headers:Automattic\WooCommerce\HttpClient\Request:private] => Array ( [Accept] => application/json [Content-Type] => application/json [User-Agent] => WooCommerce API Client-PHP/1.1.1 ) [body:Automattic\WooCommerce\HttpClient\Request:private] => {"product":{"title":"Premium Quality","type":"simple","regular_price":"21.99","description":"Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.","short_description":"Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.","categories":[9,14]}} )


//HttpClientException->getResponse()
Automattic\WooCommerce\HttpClient\Response Object ( [code:Automattic\WooCommerce\HttpClient\Response:private] => 201 [headers:Automattic\WooCommerce\HttpClient\Response:private] => Array ( [Server] => nginx [Date] => Mon, 26 Sep 2016 14:34:49 GMT [Content-Type] => application/json; charset=UTF-8 [Transfer-Encoding] => chunked [Connection] => keep-alive [Set-Cookie] => _icl_current_language=en; expires=Tue, 27-Sep-2016 14:34:49 GMT; Max-Age=86400; path=/ [Strict-Transport-Security] => max-age=15768000 ) [body:Automattic\WooCommerce\HttpClient\Response:private] => ) 
'

**Comment by claudiosmweb** [comment]
@MQuach17 still you server is not returning the correct value.
Need to check for fatal errors, look the error log from your server and fix the errors.

**Comment by MQuach17** [comment]
resolved, had to do something like 
`$output = $woocommerce->post('products',$data);'
'echo json_encode($output);'
