### ISSUE TITLE
problem with https://

### ISSUE THREAD

**Issue by Dewilas** [woothemes/wc-api-php#6]
Hello,

i have problem with your API client. I trying to get products from my address with https:// but i got error: Error: Consumer Secret is invalid [woocommerce_api_authentication_error].

EDITED:

in oficial website http://woothemes.github.io/woocommerce-rest-api-docs/#authentication i found this:

"Occasionally some servers may not parse the Authorization header correctly (if you see a “Consumer key is missing” error when authenticating over SSL, you have a server issue). In this case, you may provide the consumer key/secret as query string parameters."

How to fix that?

**Comment by claudiosmweb** [comment]
Please, before open any issue, read our documentation: https://github.com/woothemes/wc-api-php/blob/master/README.md

We provide an option for it: https://github.com/woothemes/wc-api-php/blob/master/README.md#client-options

![screenshot from 2016-02-10 14-15-14](https://cloud.githubusercontent.com/assets/1264099/12953253/b9245984-d000-11e5-86f0-b1ac0701a75b.png)
