### ISSUE TITLE
Troubles with product categories actions 

### ISSUE THREAD

**Issue by owl1n** [woothemes/wc-api-php#8]
Hello everybody.
->post('products/categories') - doesnt return insert category. Its return always random category in system. It's your bug or WooCoommerce?
Why ->get('products/categories') not accept array args? If i want to get category with name 'Test' i always saw all categories in system. Bug or what?

**Comment by claudiosmweb** [comment]
I don't see any issue with issue in this wrapper or any bug.
Please read the REST API docs: http://woothemes.github.io/woocommerce-rest-api-docs/

**Comment by owl1n** [comment]
Okay, look. I have 4 categories in the system:
`['product_categories'] => { 'id' => 334, 'name' => 'Test Cat 1'}, { 'id' => 335, 'name' => 'Test Cat 2' }, { 'id' => 336, 'name' => 'Test Cat 3' }, { 'id' => 337, 'name' => 'Test Cat 4' } `

Now, i insert new category with this action `$model->post('product/categories', ['product_category' => ['name' => 'Test Cat 5']]);`
AND, API returned not insert category, api return category with id 336 (Test Cat 3). Its no bug?

**Comment by claudiosmweb** [comment]
Still not an bug with this wrapper! Who returns the wrong ID? This wrapper or WooCommerce?
If isn't this wrapper, you are reporting in the wrong place.
And I have already answered your issue on WooCommerce repo.
